"""Add updated at

Revision ID: fcec675136a0
Revises: 965a670279d6
Create Date: 2024-12-13 12:35:51.062875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcec675136a0'
down_revision: Union[str, None] = '965a670279d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('updeted_at', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('updeted_at', sa.Date(), nullable=True))
    op.add_column('readers', sa.Column('updeted_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'updeted_at')
    op.drop_column('books', 'updeted_at')
    op.drop_column('author', 'updeted_at')
    # ### end Alembic commands ###
